In [7]:
import pandas as pd
import requests

## Learn about dataset sizes

In [2]:
# There are 13 tables and we want to fetch data from them
table_names = [
    'elspotprices',
    'afrrreservesdk1',
    'capacityauctiondk1',
    'capacityauctiondk2',
    'fcrreservesdk1',
    'fcrreservesdk2',
    'mfrrreservesdk1',
    'mfrrreservesdk2',
    'realtimemarket',
    'electricitybalance',
    'electricitybalancenonv',
    'nordpoolmarket',
    'transmissionlines'
]

In [4]:
df = pd.DataFrame()

In [23]:
table_names_to_columns = {
    'elspotprices': [
        "HourUTC",
        "HourDK",
        "PriceArea",
        "SpotPriceDKK",
        "SpotPriceEUR",
    ],
    'transmissionlines': [
        "HourUTC",
        "HourDK",
        "PriceArea",
        "ConnectedArea",
        "ImportCapacity",
        "ExportCapacity",
        "ScheduledExchangeDayAhead",
        "ScheduledExchangeIntraday",
        "PhysicalExchangeNonvalidated",
        "PhysicalExchangeSettlement",
        "CongestionIncomeDKK",
        "HomePriceDKK",
        "ConnectedPriceDKK",
        "CongestionIncomeEUR",
        "HomePriceEUR",
        "ConnectedPriceEUR",
    ]
}

In [59]:
## fetch data for one month
def fetchData(tableName):
    sql = f"""
    SELECT {', '.join([f'"{column}"' for column in table_names_to_columns[tableName]])}
    FROM {tableName}
    WHERE "HourUTC" >= '2018-12-01 00:00' AND "HourUTC" < '2019-01-01 00:00'
    ORDER BY 1 DESC
    """
    
    url = 'https://api.energidataservice.dk/datastore_search_sql?sql=' + sql.replace('\n', ' ')
    
    records = requests.get(url).json()["result"]["records"]
    return pd.DataFrame.from_records(records)

In [60]:
transmissionlines = fetchData('transmissionlines').set_index(
    ["HourUTC",
    "HourDK",
    "PriceArea",
    "ConnectedArea",]
).unstack(["PriceArea", "ConnectedArea",])
transmissionlines.head()

                                              HomePriceEUR                \
PriceArea                                              DK2
ConnectedArea                                          SE4    DK1     DE
HourUTC                   HourDK
2018-12-01T00:00:00+00:00 2018-12-01T01:00:00        42.09  42.09  42.09
2018-12-01T01:00:00+00:00 2018-12-01T02:00:00        41.07  41.07  41.07
2018-12-01T02:00:00+00:00 2018-12-01T03:00:00        42.05  42.05  42.05
2018-12-01T03:00:00+00:00 2018-12-01T04:00:00        43.50  43.50  43.50
2018-12-01T04:00:00+00:00 2018-12-01T05:00:00        43.37  43.37  43.37

                                                                           \
PriceArea                                        DK1
ConnectedArea                                    SE3    NO2    DK2     DE
HourUTC                   HourDK
2018-12-01T00:00:00+00:00 2018-12-01T01:00:00  42.09  42.09  42.09  42.09
2018-12-01T01:00:00+00:00 2018-12-01T02:00:00  42.03  42.03  42.03  42.03
2018-12-01T02:00:00+00:00 2018-12-01T03:00:00  42.05  42.05  42.05  42.05
2018-12-01T03:00:00+00:00 2018-12-01T04:00:00  43.57  43.57  43.57  43.57
2018-12-01T04:00:00+00:00 2018-12-01T05:00:00  43.37  43.37  43.37  43.37

                                              ImportCapacity                \
PriceArea                                                DK2
ConnectedArea                                            SE4    DK1     DE
HourUTC                   HourDK
2018-12-01T00:00:00+00:00 2018-12-01T01:00:00         1300.0  590.0  600.0
2018-12-01T01:00:00+00:00 2018-12-01T02:00:00         1300.0  590.0  600.0
2018-12-01T02:00:00+00:00 2018-12-01T03:00:00         1300.0  590.0  600.0
2018-12-01T03:00:00+00:00 2018-12-01T04:00:00         1300.0  590.0  600.0
2018-12-01T04:00:00+00:00 2018-12-01T05:00:00         1300.0  590.0  600.0

                                               ... ScheduledExchangeDayAhead  \
PriceArea                                      ...                       DK1
ConnectedArea                                  ...                       NO2
HourUTC                   HourDK               ...
2018-12-01T00:00:00+00:00 2018-12-01T01:00:00  ...                   -1434.4
2018-12-01T01:00:00+00:00 2018-12-01T02:00:00  ...                   -1532.0
2018-12-01T02:00:00+00:00 2018-12-01T03:00:00  ...                   -1532.0
2018-12-01T03:00:00+00:00 2018-12-01T04:00:00  ...                   -1396.3
2018-12-01T04:00:00+00:00 2018-12-01T05:00:00  ...                   -1081.0

                                                             \
PriceArea
ConnectedArea                                    DK2     DE
HourUTC                   HourDK
2018-12-01T00:00:00+00:00 2018-12-01T01:00:00  516.7 -683.3
2018-12-01T01:00:00+00:00 2018-12-01T02:00:00  600.0 -681.0
2018-12-01T02:00:00+00:00 2018-12-01T03:00:00  559.2 -603.4
2018-12-01T03:00:00+00:00 2018-12-01T04:00:00  600.0 -700.0
2018-12-01T04:00:00+00:00 2018-12-01T05:00:00  416.1 -600.0

                                              PhysicalExchangeSettlement  \
PriceArea                                                            DK2
ConnectedArea                                                        SE4
HourUTC                   HourDK
2018-12-01T00:00:00+00:00 2018-12-01T01:00:00                  1031.4736
2018-12-01T01:00:00+00:00 2018-12-01T02:00:00                  1030.1235
2018-12-01T02:00:00+00:00 2018-12-01T03:00:00                  1032.7918
2018-12-01T03:00:00+00:00 2018-12-01T04:00:00                   994.9400
2018-12-01T04:00:00+00:00 2018-12-01T05:00:00                   808.6500

                                                                        \
PriceArea                                                          DK1
ConnectedArea                                    DK1       DE      SE3
HourUTC                   HourDK
2018-12-01T00:00:00+00:00 2018-12-01T01:00:00 -260.1 -584.175  388.501
2018-12-01T01:00:00+00:00 2018-12-01T02:00:00 -267.5 -584.250  273.370
2018-12-01T02:00:00+00:00 2018-12-01T03:00:00 -327.4 -584.400  204.148
2018-12-01T03:00:00+00:00 2018-12-01T04:00:00 -313.7 -584.400  353.334
2018-12-01T04:00:00+00:00 2018-12-01T05:00:00 -110.8 -584.325  371.848


PriceArea
ConnectedArea                                       NO2    DK2      DE
HourUTC                   HourDK
2018-12-01T00:00:00+00:00 2018-12-01T01:00:00 -1263.011  260.1 -320.15
2018-12-01T01:00:00+00:00 2018-12-01T02:00:00 -1357.403  267.5 -208.15
2018-12-01T02:00:00+00:00 2018-12-01T03:00:00 -1367.928  327.4 -297.32
2018-12-01T03:00:00+00:00 2018-12-01T04:00:00 -1193.669  313.7 -308.02
2018-12-01T04:00:00+00:00 2018-12-01T05:00:00  -860.742  110.8 -273.19

[5 rows x 84 columns]

In [48]:
transmissionlines.to_excel("transmissionlines.xlsx")

In [54]:
transmissionlines.to_json("transmissionlines.json")

In [57]:
# The JSON file weighs about 4MB that is for one month from one (largest) table, 
# => total possible (noone will probably ever request such a report, but still) size estimate is 6.24 GB
# and that's a really overestimation, because elspotprices.json takes 0.625MB

print(4 * 
      13 # total number of tables
      *
      12 # months
      *
      10 # years
     )

6240

In [61]:
elspotprices = fetchData('elspotprices').set_index(
    ["HourUTC",
    "HourDK",
    "PriceArea",]).unstack(["PriceArea"])
elspotprices.head()

                                              SpotPriceEUR                \
PriceArea                                               DE    DK1    DK2
HourUTC                   HourDK
2018-12-01T00:00:00+00:00 2018-12-01T01:00:00        42.09  42.09  42.09
2018-12-01T01:00:00+00:00 2018-12-01T02:00:00        42.03  42.03  41.07
2018-12-01T02:00:00+00:00 2018-12-01T03:00:00        42.05  42.05  42.05
2018-12-01T03:00:00+00:00 2018-12-01T04:00:00        44.56  43.57  43.50
2018-12-01T04:00:00+00:00 2018-12-01T05:00:00        43.37  43.37  43.37

                                                                           \
PriceArea                                        NO2    SE3    SE4 SYSTEM
HourUTC                   HourDK
2018-12-01T00:00:00+00:00 2018-12-01T01:00:00  43.78  42.09  42.09  43.45
2018-12-01T01:00:00+00:00 2018-12-01T02:00:00  43.54  41.07  41.07  43.01
2018-12-01T02:00:00+00:00 2018-12-01T03:00:00  43.47  42.05  42.05  43.09
2018-12-01T03:00:00+00:00 2018-12-01T04:00:00  43.57  43.50  43.50  43.44
2018-12-01T04:00:00+00:00 2018-12-01T05:00:00  43.95  43.37  43.37  43.65

                                              SpotPriceDKK                  \
PriceArea                                               DE     DK1     DK2
HourUTC                   HourDK
2018-12-01T00:00:00+00:00 2018-12-01T01:00:00       314.08  314.08  314.08
2018-12-01T01:00:00+00:00 2018-12-01T02:00:00       313.63  313.63  306.46
2018-12-01T02:00:00+00:00 2018-12-01T03:00:00       313.78  313.78  313.78
2018-12-01T03:00:00+00:00 2018-12-01T04:00:00       332.51  325.12  324.60
2018-12-01T04:00:00+00:00 2018-12-01T05:00:00       323.63  323.63  323.63


PriceArea                                         NO2     SE3     SE4  SYSTEM
HourUTC                   HourDK
2018-12-01T00:00:00+00:00 2018-12-01T01:00:00  326.69  314.08  314.08  324.22
2018-12-01T01:00:00+00:00 2018-12-01T02:00:00  324.90  306.46  306.46  320.94
2018-12-01T02:00:00+00:00 2018-12-01T03:00:00  324.37  313.78  313.78  321.54
2018-12-01T03:00:00+00:00 2018-12-01T04:00:00  325.12  324.60  324.60  324.15
2018-12-01T04:00:00+00:00 2018-12-01T05:00:00  327.95  323.63  323.63  325.72

In [58]:
elspotprices.to_json("elspotprices.json")